### ISSUE TITLE
Internal compiler expectation broken bug

### ISSUE THREAD

**Issue by asevos** [roc-lang/roc#7195] opened 2024-11-04 15:55 UTC
Hi! I am new to Roc and I'm exploring tutorial at the moment. I was trying to write a basic function when I stumbled upon this bug: 
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
ambient functions don't unify
Location: crates/compiler/unify/src/unify.rs:202:18
```
Here is a Roc file that produces this issue: 
```roc
app [main] {
    cli: platform "https://github.com/roc-lang/basic-cli/releases/download/0.15.0/SlwdbJ-3GR7uBWQo6zlmYWNYOxnvo8r6YABXD-45UOw.tar.br",
}

import cli.Stdout

main =
    strs = ["lol", "kek", "cheburek"]
    dbg count strs

    Stdout.line! "Done"

count : List * -> Int *
count = \list ->
    when list is
        [] -> 0
        [_] -> 1
        [_, .. as tail] -> 1 + count tail
```
The problem seems to be in incorrect type annotation: when I comment it out, everything works.

UPD: if I remove type annotation, LSP hint for type of `count` would be `List * -> Num *`. But if I use this annotation in code as `count : List * -> Num *`, compiler also panics: 
```
thread 'main' panicked at crates/compiler/mono/src/borrow.rs:396:34:
internal error: entered unreachable code:
        No borrow signature for LambdaName { name: `15.IdentId(5)`, niche: Niche(Captures([])) } layout.

        Tip 1: This can happen when you call a function with less arguments than it expects.
        Like `Arg.list!` instead of `Arg.list! {}`.
        Tip 2: `roc check yourfile.roc` can sometimes give you a helpful error.

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`roc check`, of course, yields no errors

**Comment by Anton-4** [comment] 2024-11-04 18:44
Hi @asevos!
This appears to be a duplicate of https://github.com/roc-lang/roc/issues/6824 so I'm going to close this issue.

**Closed by Anton-4** 2024-11-04 18:44 UTC
