### ISSUE TITLE
Undefined symbol crash

### ISSUE THREAD

**Issue by JanCVanB** [roc-lang/roc#3938] opened 2022-08-31 05:06 UTC
I don't know what's happening here, but it could be a weird interaction between Nix & Fedora 36:

```
[jan@framey roc-plotters]$ roc dev examples/math.roc 
🔨 Rebuilding host...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+272, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+32)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "sin", address: +0, size: +0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/lib.rs:2617:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey roc-plotters]$ 
```

**Comment by Anton-4** [comment] 2022-08-31 09:33
This is a duplicate of #3609

**Closed by Anton-4** 2022-08-31 09:33 UTC
