### ISSUE TITLE
changing browser tabs sends input buffer to repl

### ISSUE THREAD

**Issue by dankeyy** [roc-lang/roc#5182] opened 2023-03-23 20:14 UTC
Don't really have a neat way to show repro here but try to put some text in the text box, move to a different tab, and you will see how the text was sent to repl, even though you haven't pressed enter

Tested on firefox, linux

**Comment by Anton-4** [comment] 2023-03-24 09:53
I'm going to close this as a duplicate of #5136 but thanks for reporting it anyway :)

**Closed by Anton-4** 2023-03-24 09:53 UTC
