### ISSUE TITLE
`roc run` crashes with called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#4842] opened 2022-12-31 15:59 UTC
I've tried to minimise this as much as I can. 

```sh
% roc run test.roc
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/compiler/mono/src/ir.rs:5640:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```elixir
app "aoc-2022"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.1.2/3bKbbmgtIfOyC6FviJ9o8F8xqKutmXgjCJx3bMfVTSo.tar.br" }
    imports [
        pf.Stdout,
        pf.Task.{ Task },
        pf.File,
        pf.Path.{ Path },
    ]
    provides [main] to pf

main : Task {} []
main =

    task =
        fsSample = buildDirectoryListing [] 
        fileInput <- File.readUtf8 (Path.fromStr "") |> Task.map Str.toUtf8 |> Task.await
        _ = part1 fsSample
        Stdout.line ""

    Task.onFail task \_ -> crash "Oops, something went wrong."

part1 : FileSystem -> U64
part1 = \fs ->
    fs 
    |> Dict.keys
    |> List.keepOks \path -> dirSize fs path
    |> List.keepIf \size -> size <= 100_000
    |> List.sum

FileSystem : Dict (List Str) Entry
Entry : [ File U64, Folder U64 ]

buildDirectoryListing : List LineOutput -> FileSystem 
buildDirectoryListing = \lo ->
    List.walk lo {cwd:List.withCapacity 10, fs : Dict.empty} \{cwd, fs}, line ->
        when line is
            FileListing size name ->
                path = List.append cwd name |> Str.joinWith "/"
                entry = File size
                xfs = 
                    fs 
                    |> Dict.insert path entry
                    |> updateParentSizes (Str.joinWith cwd "/") size

                {cwd, fs : xfs}
            _ ->
                {cwd, fs}
    |> .fs

updateParentSizes : FileSystem, List Str, U64 -> FileSystem
updateParentSizes = \fs, path, size ->

    xfs = Dict.insert fs path (Folder 0)

    when List.dropLast path is 
        [] -> xfs
        parent -> updateParentSizes xfs parent size    

dirSize : FileSystem, List Str -> Result U64 [NotFolder]
dirSize = \fs, path ->
    when Dict.get fs path is 
        Ok (Folder currentSize) -> Ok currentSize
        _ -> Err NotFolder

LineOutput : [ FileListing U64 Str ]

sampleInput = Str.toUtf8 ""

```

**Comment by fwgreen** [comment] 2024-01-02 02:05
Maybe this might be related?
```elm
app "bug"
    packages {
        pf: "https://github.com/roc-lang/basic-cli/releases/download/0.7.0/bkGby8jb0tmZYsy2hg1E_B2QrCgcSTxdUlHtETwm5m4.tar.br",
    }
    imports [
        pf.Stdout, 
    ]
    provides [main] to pf

main =
    dbg List.withCapacity 10

    Stdout.line 
        """
        done
        """
```
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/compiler/mono/src/ir.rs:6156:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by skyqrose** [comment] 2024-11-13 22:01
Duplicate of https://github.com/roc-lang/roc/issues/4776
They crash on the same line, though the line number changed between the two reports. The code at the time this issue was filed:
https://github.com/roc-lang/roc/blob/ea53a50447c0cf9a1c5f9c66bf9cab79e71f0866/crates/compiler/mono/src/ir.rs#L5640
The code at the time that issue was filed:
https://github.com/roc-lang/roc/blob/4315a36e905218f85291172bbf9c07a7079ca216/crates/compiler/mono/src/ir.rs#L5714

**Closed by skyqrose** 2024-11-13 22:01 UTC
Labels: bug
