### ISSUE TITLE
Roc error reporing does not add a new line

### ISSUE THREAD

**Issue by Unaimend** [roc-lang/roc#4911] opened 2023-01-16 21:35 UTC
![image](https://user-images.githubusercontent.com/7808379/212768557-28070643-543a-42e2-8926-e2e88b18117b.png)

As you can see the roc compiler does not add a newline after the last sentence.
I tried looking into the compiler but could find the error-reporting part.

Actual output:
```
(base) td@td-debian:~/dev/roc/tutorial$ roc test.roc 
── WEIRD APP NAME ─────────────────────────────────────────────────── test.roc ─

I am partway through parsing a header, but got stuck here:

1│  app "hello
        ^

I am expecting an application name next, like app "main" or
app "editor". App names are surrounded by quotation marks.(base) td@td-debian:~/dev/roc/tutorial$
```

Expected output:
```
(base) td@td-debian:~/dev/roc/tutorial$ roc test.roc 
── WEIRD APP NAME ─────────────────────────────────────────────────── test.roc ─

I am partway through parsing a header, but got stuck here:

1│  app "hello
        ^

I am expecting an application name next, like app "main" or
app "editor". App names are surrounded by quotation marks.
(base) td@td-debian:~/dev/roc/tutorial$ 
```

**Comment by Unaimend** [comment] 2023-01-16 21:49
Roc version: roc nightly pre-release, built from commit 46d69e8 on Sa 14 Jan 2023 10:55:51 UTC

**Comment by JRI98** [comment] 2024-11-27 17:16
Can't reproduce. Maybe fixed by https://github.com/roc-lang/roc/pull/6549

**Closed** 2024-11-27 23:27 UTC
Labels: bug, parsing, error-messages
