### ISSUE TITLE
Another race condition?

### ISSUE THREAD

**Issue by folkertdev** [roc-lang/roc#1097] opened 2021-03-22 12:08 UTC
I'm getting this error sometimes

```
thread 'cli_run::base64' panicked at 'Unrecognized non-builtin function: "Effect_putLine_1"

Symbol: `fx.Effect.putLine`
Layout: FunctionPointer([Builtin(Str)], Closure([Struct([])], ClosureLayout { captured: [], layout: Struct([Builtin(Str)]) }, Struct([])))

Is the function defined? If so, maybe there is a problem with the layout
thread 'main' panicked at 'Unrecognized non-builtin function: "Effect_putLine_1" (symbol: `fx.Effect.putLine`)', compiler/gen/src/llvm/build.rs:3503:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
', cli/tests/cli_run.rs:57:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Sounds like a race condition where the effect module is not loaded

**Comment by skyqrose** [comment] 2024-11-11 16:18
There have been so many changes to effect modules since this task was created, so this bug has probably disappeared. And if it only happens intermittently, trying to reproduce it will be difficult. Closing this task so that nobody tries to work on it. If anybody sees a similar error, it'll pop up again as a new bug report.

**Closed by skyqrose** 2024-11-11 16:18 UTC
Labels: bug, loading
