### ISSUE TITLE
assertion failure when using `walk` with `joinMap`

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5619] opened 2023-06-27 15:36 UTC
To reproduce:

1. Check out the [`dict-set` branch](https://github.com/roc-lang/roc/pull/5620/files) (if it hasn't already been merged into `main`)
2. In `roc repl`, run:
 
`\list, dictFromElem -> List.walk list (Dict.empty {}) \dict, elem -> Dict.joinMap dict \_, _ -> dictFromElem elem`

It panics with:

> assertion failed: unspecialized.is_empty()', crates/compiler/mono/src/ir.rs:5879:9

This was an attempt to reproduce https://github.com/roc-lang/roc/issues/5617 using `Dict `instead of `Task`, but it might be a different issue since it happens in mono instead of subs.

**Comment by ayazhafiz** [comment] 2023-06-29 22:48
Duplicate of #4478

**Closed by ayazhafiz** 2023-06-29 22:48 UTC
Labels: bug, mono
