### ISSUE TITLE
`roc check IDCounter.roc` also checks main.roc 

### ISSUE THREAD

**Issue by planmac** [roc-lang/roc#7074] opened 2024-09-12 22:05 UTC
Got this error when running: `roc check IDCounter.roc` on the Full Code found at the end of this pg: 
`https://www.roc-lang.org/examples/RecordBuilder/README.html`

The full error message:
`An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Outstanding references to the derived module
Location: crates/compiler/load_internal/src/file.rs:3298:29`

Platform: Apple silicon

**Comment by Anton-4** [comment] 2024-09-15 07:56
Thanks for reporting this @planmac!

I was not able to reproduce this error on ubuntu, can you share the output of `roc version`?

**Comment by planmac** [comment] 2024-09-15 22:15
roc nightly pre-release, built from commit 9a4d556725 on Sat Sep  7 09:14:19 UTC 2024

**Comment by Anton-4** [comment] 2024-09-16 14:35
I'm still not able to reproduce it on ubuntu with that exact version. In 10 days I will have access to my mac again, and I'll give it a try then.

**Comment by JRI98** [comment] 2024-09-16 14:52
Can't reproduce on Apple M1

**Comment by planmac** [comment] 2024-09-18 14:32
OK, I replicated the error - if there is a `main.roc` file in the same dir as the file being checked then `roc check <anything>` attempts to compile/invoke that main.roc file, leading to the compiler error. I tested this in a clean dir:
```
mkdir Roc
cd Roc
cp ../IDCounter.roc ./
touch main.roc
roc check IDCounter.roc
```
.. throws a `-- MISSING HEADER in main.roc --` error 
Not sure if this is a _feature_ or a _bug_ ??

**Comment by Anton-4** [comment] 2024-09-21 16:27
Thanks for investigating this further @planmac, I've [started a discussion on zulip](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/roc.20check.20module/near/471955092).

**Comment by Anton-4** [comment] 2024-09-22 08:00
Looks like the original error also happens when I put a valid hello world in main.roc:
```
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Outstanding references to the derived module
Location: crates/compiler/load_internal/src/file.rs:3298:29
```
This should definitely not happen.

**Comment by gamebox** [comment] 2024-12-05 01:05
I think this is a dup of an issue I closed earlier this week, let me pull it up.

https://github.com/roc-lang/roc/issues/7175

Check with latest (main/master) but this should be fixed.  I'll close for now, but feel free to reopen if you still see it.

**Closed by gamebox** 2024-12-05 01:05 UTC
Labels: bug, P-medium
