### ISSUE TITLE
Pattern matching record with closed union fails (derivative

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#6162] opened 2023-12-03 02:05 UTC
This fails

```
app "test" provides [check] to "./platform"
                                            
Union : [A, B]
                                            
check : Union, Union -> Nat
check = \a, b ->
    when {a, b} is
        {a: A, b: _} -> 0
        {a: B, b: A} -> 1
        {a: B, b: B} -> 2
```
Unlike #6161, this case does not panic. But the fix there will likely correspond to a fix here.

**Comment by skyqrose** [comment] 2024-11-03 02:38
I've linked to this example from #5330. Closing this one as a duplicate of that one to keep everything all in one place.

**Closed by skyqrose** 2024-11-03 02:38 UTC
