### ISSUE TITLE
Num.floor  crashes  roc_nightly-linux_x86_64-2023-05-30-ef05ec6

### ISSUE THREAD

**Issue by salarii** [roc-lang/roc#5490] opened 2023-05-31 12:36 UTC
app "exp"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.3.1/97mY3sUwo433-pcnEQUlMhn-sWiIf_J9bPhcAFZoqY4.tar.br" }
    imports [pf.Stdout] 
    provides [main] to pf

main =

    dbg  Num.floor  2.4
    Stdout.line "I'm a Roc application!"

**Comment by salarii** [comment] 2023-05-31 12:43
roc dev  reprod.roc 
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+3382, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+26)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "floor", address: +0, size: +0, kind: Label, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/elf.rs:1482:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Anton-4** [comment] 2023-05-31 12:45
Hi @salarii, this is a duplicate of #3609.
As a temporary workaround, you can use the flag `--linker=legacy` as follows:
```
roc dev examples/helloWorld.roc --linker=legacy
```

**Closed by Anton-4** 2023-05-31 12:45 UTC
