### ISSUE TITLE
repl panics with undefined variable 

### ISSUE THREAD

**Issue by Robin40** [roc-lang/roc#6528] opened 2024-02-20 01:50 UTC
Original title: repl panics with string interpolation of undefined variable 

If I do "$(a)" without previously defining the variable `a` on REPL it crashes:

thread 'main' panicked at 'not yet implemented: immediate subtractions with values greater than 12bits', crates/compiler/gen_dev/src/generic64/aarch64.rs:1861:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Edit: It's a more general issue: it also happens with `Str.concat a ""` and `b + 1`, but not with `a`.

Tested on roc_nightly-macos_apple_silicon-2024-02-16-943d7a3cdf

This may be related to #5708, I'm not sure if it should be a different issue as the error message is different.

**Comment by skyqrose** [comment] 2024-11-23 20:04
This is a caused by a `todo!`, it's just not implemented yet. Specifically this one: https://github.com/roc-lang/roc/blob/22423ca98bef41e2f55ae54e11c632bd0610c241/crates/compiler/gen_dev/src/generic64/aarch64.rs#L1861

Someone else ran into the same `todo!` here: https://github.com/roc-lang/roc/issues/6810

Since there's a todo in the source code to remind us to implement it some time, I don't think we need an issue to stay open for it, so I'm closing this issue.

**Closed by skyqrose** 2024-11-23 20:04 UTC
