### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by BashkaMen** [roc-lang/roc#7066] opened 2024-09-08 14:13 UTC
i use exmple 

```
app [Model, server] {
    pf: platform "https://github.com/roc-lang/basic-webserver/releases/download/0.9.0/taU2jQuBf-wB8EJb0hAkrYLYOGacUU5Y9reiHG45IY4.tar.br",
}

import pf.Stdout
import pf.Http exposing [Request, Response]
import pf.Utc

# Model is produced by `init`.
Model : {}

# With `init` you can set up a database connection once at server startup,
# generate css by running `tailwindcss`,...
# In this case we don't have anything to initialize, so it is just `Task.ok {}`.

server = { init: Task.ok {}, respond }

respond : Request, Model -> Task Response [ServerErr Str]_
respond = \req, _ ->
    # Log request datetime, method and url
    datetime = Utc.now! |> Utc.toIso8601Str

    Stdout.line! "$(datetime) $(Http.methodToStr req.method) $(req.url)"

    Task.ok { status: 200, headers: [], body: Str.toUtf8 "<b>Hello, web!</b></br>" }
```

run roc dev

```An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Undefined Symbol in relocation, (+405, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+cd)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "roc_realloc", address: +0, size: +0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })
Location: crates/linker/src/elf.rs:1452:25```

**Comment by BashkaMen** [comment] 2024-09-08 14:15
my devcontainer.json

```
{
    "build": {
        "dockerfile": "Dockerfile"
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "IvanDemchenko.roc-lang-unofficial"
            ],
            "settings": {
                "roc-lang.language-server.exe": "/roc-lang/roc_nightly-linux_x86_64-2024-09-07-9a4d556/roc_language_server",
                "editor.formatOnSave": true
            }
        }
    },
    "forwardPorts": [
        8000
    ],
    "remoteUser": "root"
}
```

Dockerfile
```
FROM ubuntu:22.04

# Обновление системы и установка необходимых инструментов
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    build-essential \
    libc-dev \
    binutils \
    && rm -rf /var/lib/apt/lists/*

# Установка Roc
WORKDIR /roc-lang
RUN wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz \
    && tar -xf roc_nightly-linux_x86_64-latest.tar.gz \
    && rm roc_nightly-linux_x86_64-latest.tar.gz

RUN ls

ENV ROC_DIR="/roc-lang/roc_nightly-linux_x86_64-2024-09-07-9a4d556"
ENV PATH="${ROC_DIR}:${PATH}"

# Проверка установки Roc
RUN roc --version

# Создание рабочей директории
WORKDIR /app

# Команда, выполняемая при запуске контейнера
CMD ["/bin/bash"]
```

**Comment by Anton-4** [comment] 2024-09-09 09:50
Hi @BashkaMen,
On linux you need to use the flag `--linker=legacy` (`roc dev --linker=legacy`) due to https://github.com/roc-lang/roc/issues/3609.
I've made another high priority issue to improve the error message in this case https://github.com/roc-lang/roc/issues/7068.

**Comment by BashkaMen** [comment] 2024-09-09 09:54
@Anton-4 можем пообщаться в телеге? Есть еще вопросики :)

**Comment by Anton-4** [comment] 2024-09-09 09:59
У меня нет Telegram, но вы можете задать все интересующие вас вопросы в нашем групповом чате по адресу: https://roc.zulipchat.com/

**Comment by BashkaMen** [comment] 2024-09-09 10:00
Is legacy bad? Why am I using something old using a new language? :)

**Comment by Anton-4** [comment] 2024-09-09 10:03
It's not bad, it's only slower. Our own fast linker still has some issues, like the one you encountered earlier, so that is why we keep the legacy linker available.

**Comment by lukewilliamboswell** [comment] 2024-09-10 21:10
This looks to be a duplicate of #7070 which is a slightly smaller repro. 

Anton has linked an issue to improve the error message. 

@BashkaMen would you be ok closing this issue in favour of #7070?

**Comment by BashkaMen** [comment] 2024-09-10 21:38
txt

**Closed** 2024-09-10 21:38 UTC
Labels: bug, linking
