### ISSUE TITLE
Pattern matching record with closed union fails

### ISSUE THREAD

**Issue by ayazhafiz** [roc-lang/roc#6161] opened 2023-12-03 02:04 UTC
```
app "test" provides [check] to "./platform"
                                            
Union : [A, B]
                                            
check : Union, Union -> Nat
check = \a, b ->
    when {a, b} is
        {a: A} -> 0
        {a: B, b: A} -> 1
        {a: B, b: B} -> 2
```

this currently panics. Likely to be related and similar to #6154

**Comment by skyqrose** [comment] 2024-11-03 02:37
I've linked to this example from #6154. Closing this one as a duplicate of that one to keep everything all in one place.

**Closed by skyqrose** 2024-11-03 02:37 UTC
