### ISSUE TITLE
Optional record fields type check as required

### ISSUE THREAD

**Issue by mulias** [roc-lang/roc#6101] opened 2023-11-27 04:49 UTC
```
app "main"
    packages {
        cli: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br",
    }
    imports [
        cli.Stdout,
    ]
    provides [main] to cli

fields : { x : Str, y ? Str } -> Str
fields = \{x} -> x

main =
    Stdout.line "\(fields {x: "A", y: "A"}) \(fields {x: "A"})"
```

```
$ roc check

── TYPE MISMATCH ─────────────────────────────────── main.roc ─

This 1st argument to fields has an unexpected type:

14│      Stdout.line "\(fields {x: "A", y: "A"}) \(fields {x: "A"})"
                                                          ^^^^^^^^

The argument is a record of type:

    { … }

But fields needs its 1st argument to be:

    { y : Str, … }

Tip: Looks like the y field is missing.

────────────────────────────────────────────────────────────────────────────────

1 error and 0 warnings found in 63 ms.
```

**Comment by skyqrose** [comment] 2024-11-23 20:46
Duplicate of https://github.com/roc-lang/roc/issues/6423

**Closed** 2024-11-23 20:47 UTC
Labels: bug
