### ISSUE TITLE
wrong "when does not cover all the possibilities"

### ISSUE THREAD

**Issue by Anton-4** [roc-lang/roc#6561] opened 2024-03-06 19:00 UTC
```
app "helloWorld"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.8.1/x8URkvfyi9I0QhmVG98roKBUs_AZRkLFwFJVJ3942YA.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main =
    Stdout.line "Hello, World!"

testWhen = \lstA, lstB ->
    when (lstA, lstB) is
        ([], _) -> 5
        (_, []) -> 6
        (_, [_]) -> 7
        (_, [_, .. as tail]) -> List.sum(tail)


expect (testWhen [1] [1] == 7)
```

```
── UNSAFE PATTERN in examples/helloWorld.roc ───────────────────────────────────

This when does not cover all the possibilities:

10│>      when (lstA, lstB) is
11│>          ([], _) -> 5
12│>          (_, []) -> 6
13│>          (_, [_]) -> 7
14│>          (_, [_, .. as tail]) -> List.sum(tail)

Other possibilities include:

    ( [_, ..], _ )

I would have to crash if I saw one of those! Add branches for them!

────────────────────────────────────────────────────────────────────────────────

```

**Comment by Anton-4** [comment] 2024-03-06 19:02
This similar version does work:
```
testWhen = \lst ->
    when lst is
        [] -> 5
        [_] -> 6
        [_, .. as tail] -> List.sum(tail)


expect (testWhen [1] == 6)
```

**Comment by Anton-4** [comment] 2024-03-06 19:03
Possibly related to #6154

**Comment by skyqrose** [comment] 2024-11-03 02:37
I've linked to this example from #6154. Closing this one as a duplicate of that one to keep everything all in one place.

**Closed by skyqrose** 2024-11-03 02:37 UTC
