### ISSUE TITLE
Roc panics with `Unification failed in deriver - that's a deriver bug!`

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5251] opened 2023-04-04 07:43 UTC
Saved the files in this [branch](https://github.com/lukewilliamboswell/roc/tree/deriver-bug). I was adding an additional tag to decode `DecodeError : [TooShort, NotARecord]` for fault finding when I encountered this bug. 

```
$ cargo run -- test crates/compiler/builtins/roc/Json.roc 
   Compiling roc_builtins v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/builtins)
   Compiling roc_mono v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/mono)
   Compiling roc_load_internal v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/load_internal)
   Compiling roc_alias_analysis v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/alias_analysis)
   Compiling roc_gen_dev v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/gen_dev)
   Compiling roc_gen_wasm v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/gen_wasm)
   Compiling roc_gen_llvm v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/gen_llvm)
   Compiling roc_load v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/load)
   Compiling roc_linker v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/linker)
   Compiling roc_ast v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/ast)
   Compiling roc_repl_eval v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/repl_eval)
   Compiling roc_code_markup v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/code_markup)
   Compiling roc_build v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/compiler/build)
   Compiling roc_docs v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/docs)
   Compiling roc_repl_expect v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/repl_expect)
   Compiling roc_repl_cli v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/repl_cli)
   Compiling roc_glue v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/glue)
   Compiling roc_cli v0.0.1 (/Users/luke/Documents/GitHub/roc/crates/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 16.08s
     Running `target/debug/roc test crates/compiler/builtins/roc/Json.roc`
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at 'Unification failed in deriver - that's a deriver bug!', crates/compiler/derive/src/util.rs:96:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ayazhafiz** [comment] 2023-04-10 14:21
Was this in a debug or release build?

**Comment by ayazhafiz** [comment] 2023-04-10 18:36
This is a duplicate of https://github.com/roc-lang/roc/issues/4693 - unfortunately that issue will take some design work so I think the fix will not be easy. In the meantime, could you use a record with two fields, or a different type, in the test @lukewilliamboswell ? That should avoid this.

**Comment by ayazhafiz** [comment] 2023-04-10 21:40
@lukewilliamboswell this is expected - if the public types in `Decode.roc` or other builtin-ability modules change, we need to update the compiler implementation as well, as it does not at hand know about the exposed type elsewhere. I'm happy to coordinate compiler changes as needed for the updates you want to make.

**Closed** 2023-04-10 21:41 UTC
Labels: bug

**Comment by lukewilliamboswell** [comment] 2023-04-10 21:56
No worries, I might leave a warning or something in comments in the file for future. Something like, any changes to exposed types requires internal compiler changes, discuss and coordinate on Zulip. or something
