### ISSUE TITLE
Update `Dict.fromList` to use tuple syntax

### ISSUE THREAD

**Issue by lukewilliamboswell** [roc-lang/roc#5295] opened 2023-04-16 06:25 UTC
Update internal representation of `Dict.fromList` to support tuple syntax.

**Current:** `fromList : List (T k v) -> Dict k v | k has Hash & Eq`

**Desired:** `fromList : List (k, v) -> Dict k v | k has Hash & Eq`

This will enable use case like the below example where a `Graph a` from list should be able to use `Dict.fromList`, but currently has a type mismatch.

```
## Graph type representing a graph as a dictionary of adjacency lists
## where each key is a vertex and each value is a list of its adjacent vertices.
Graph a := Dict a (List a) | a has Eq

## Create a Graph from an adjacency list.
fromList : List (a, List a) -> Graph a
fromList = \adjacencyList ->
    Dict.fromList adjacencyList
    |> @Graph

## Create a Graph from an adjacency list.
fromDict : Dict a (List a) -> Graph a
fromDict = @Graph
```

```

── TYPE MISMATCH ─────────────────────────── examples/GraphTraversal/Graph.roc ─

This 1st argument to fromList has an unexpected type:

21│      Dict.fromList adjacencyList
                       ^^^^^^^^^^^^^

This adjacencyList value is a:

    List (
        a,
        List a,
    )a | a has Hash & Eq, a has Hash & Eq

But fromList needs its 1st argument to be:

    List (T k v) | k has Hash & Eq
```

**Comment by tauseefmohammed2** [comment] 2023-04-16 09:47
Hi!
I would love to contribute to the repo. I saw that the issue is labelled "first time", which is perfect for me as I am new to this project and eager to get started. Could you please assign this issue to me?

**Comment by lukewilliamboswell** [comment] 2023-04-16 10:43
If you need a hand with anything, open a thread in the zulip [contributor channel](https://roc.zulipchat.com/#narrow/stream/316715-contributing). 🦘

**Closed** 2023-05-29 15:00 UTC
Labels: good first issue, builtins
