### ISSUE TITLE
`Hash.hash` does not appear in builtin docs

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#5195] opened 2023-03-25 12:16 UTC
https://www.roc-lang.org/builtins/Hash

**Comment by rtfeldman** [comment] 2023-03-25 12:16
This might be because it isn't exposed properly.

Could be related to https://github.com/roc-lang/roc/issues/5194

**Comment by skyqrose** [comment] 2024-11-05 01:39
Duplicate of https://github.com/roc-lang/roc/issues/5757

**Closed by skyqrose** 2024-11-05 01:39 UTC
Labels: bug, docs generation
