### ISSUE TITLE
Roc docs hangs indefinitely for any package depending on another package

### ISSUE THREAD

**Issue by imclerran** [roc-lang/roc#7407] opened 2024-12-23 16:39 UTC
**Description**:  
As the title suggests, `roc docs` hangs indefinitely when processing a package that depends on an external package.  

### Steps to Reproduce:  
1. Use the following files:  

**main.roc**  
```roc
package [Module] {
    ex: "https://github.com/imclerran/roc-ex/releases/download/v0.1.0/t5XMk1-aApXQm_XHaZodFPrc4o5lELIADyAqnYrrCv0.tar.br",
}
```  

**Module.roc**  
```roc
module []
import ex.Example
```  

2. Run `roc docs`.  

### Expected Behavior:  
Documentation generation completes successfully without hanging.  

### Actual Behavior:  
The command hangs indefinitely, making it impossible to generate documentation for packages with dependencies.

**Comment by imclerran** [comment] 2024-12-23 16:57
Just realized this is probably a duplicate of #6889

**Comment by gamebox** [comment] 2024-12-24 01:08
I think the problem is having a module with no exports.  In a purely functional language there is reason to have a module that exports nothing.  This should probably be a really early error condition

**Comment by gamebox** [comment] 2024-12-24 01:08
The same situation seems to be the case in #6889 .

**Comment by gamebox** [comment] 2024-12-24 01:09
I've got a couple PRs in limbo right now, so I can take this on tomorrow morning

**Comment by imclerran** [comment] 2024-12-24 03:06
I don't believe it's related to the exports. The following also produces the same problem. The no-export version is just a further reduction.

**Module.roc**
```
module [value]
import ex.Example

value = Example.value
# expect value == 1
```

**Comment by gamebox** [comment] 2024-12-24 03:17
That's bizarre because platforms like basic-cli do this all the time with no issue.  So there is definitely a confounding factor.  Trying this out now on my local

**Comment by gamebox** [comment] 2024-12-24 03:28
Ah, I see - I missed the part about the external package.

**Comment by gamebox** [comment] 2024-12-24 03:28
So package + import from other package.  That's definitely a HUGE deal

**Comment by gamebox** [comment] 2024-12-24 22:24
I think I've got a fix for this.  Checking tests and other invariants.

**Closed** 2024-12-26 18:26 UTC
Labels: bug, P-high
