### ISSUE TITLE
linking error in custom JSON decoder implementation

### ISSUE THREAD

**Issue by travisstaloch** [roc-lang/roc#4236] opened 2022-10-07 09:01 UTC
Encountered this while trying to make a json float number parser.  Tried to make a minimal reproduction and this is as minimal as i could make it.

Repro: https://gist.github.com/travisstaloch/1db690d065a53558a2d20493242f313b
(See instructions at the top for running the file)

```console
$ roc version
roc nightly pre-release, built from commit 2b91154 on Sa 01 Okt 2022 09:15:07 UTC

$ RUST_BACKTRACE=1 roc examples/parser/repro.roc 
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+7036, Relocation { kind: Relative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+287)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "", address: +0, size: +0, kind: Section, section: Section(SectionIndex(+9)), scope: Compilation, weak: false, flags: Elf { st_info: +3, st_other: +0 } })', crates/linker/src/elf.rs:1288:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: roc_linker::elf::surgery_elf_help
   3: roc_linker::link_preprocessed_host
   4: roc_cli::build::build_file
   5: roc_cli::build
   6: roc::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rtfeldman** [comment] 2022-10-07 10:09
@bhansconnect this is on Debian - does it look like a linking issue to you?

**Comment by travisstaloch** [comment] 2022-10-07 14:20
was able to build and successfully run with `--linker=legacy`.  should this be closed?

**Comment by bhansconnect** [comment] 2022-10-07 14:33
Root cause is the same as #3827. Closing this as duplicate.

**Closed by bhansconnect** 2022-10-07 14:33 UTC
