### ISSUE TITLE
Crash running basic-cli program on NixOS

### ISSUE THREAD

**Issue by jwoudenberg** [roc-lang/roc#4646] opened 2022-12-01 19:32 UTC
Hi there! I'm excited to try out Roc working through Advent of Code this year. I've started out trying to run the basic-cli tutorial program, but get an error. I'm on an x86_64 NixOS 21.11 machine. I've installed Roc itself using the flake in this repo.

I realize the NixOS installation is a bit non-standard, definitely not mentioned in the tutorial, so I totally understand if this just isn't supported at the moment. But the error asked me nicely to create an issue, so here it is!

```
Downloading https://github.com/roc-lang/basic-cli/releases/download/0.1.1/zAoiC9xtQPHywYk350_b7ust04BmWLW00sjb9ZPtSQk.tar.br
    into /home/jasper/.cache/roc/packages

An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'libc::fexecve("/proc/self/fd/3", ..., ...) failed: Errno { code: 2, description: Some("No such file or directory") }', crates/cli/src/lib.rs:942:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jwoudenberg** [comment] 2022-12-01 19:52
For anyone in the same situation as me, I managed to work around the error using the `flake.nix` file in my advent of code project below. With that in place, I can run `nix develop` to start a shell in which I can use the `roc` cli to compile programs using the `basic-cli` platform.

```nix
{
  description = "groceries";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
    roc.url = "github:kubukoz/roc/fix-nix"; # See: https://github.com/roc-lang/roc/pull/4640
  };
  outputs = { self, nixpkgs, flake-utils, roc }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = import nixpkgs { inherit system; };
      in {
        devShell = (pkgs.buildFHSUserEnv {
          name = "roc-in-fhs-userenv";
          targetPkgs = _: [ roc.packages."${system}".default ];
          runScript = "bash";
        }).env;
      });
}
```

**Comment by nat-418** [comment] 2024-04-06 07:34
NixOS 21.11 is no longer supported, and I cannot reproduce this bug. Can we close it?

**Comment by Anton-4** [comment] 2024-04-06 09:07
Yeah we test basic-cli with nix in CI now, so this should be good.

**Closed by Anton-4** 2024-04-06 09:07 UTC
