### ISSUE TITLE
Expect statements breaks with "a Expr::TaskAwaitBang expression was not completed removed in desugar_value_def_suffixed"

### ISSUE THREAD

**Issue by jfkonecn** [roc-lang/roc#6784] opened 2024-06-01 18:38 UTC
I'm just doing what the error told me and reporting the issue :smile: 

I added `expect 1 == 2` to the first line of the my main function and got the following error when running `roc dev`

```sh
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread '<unnamed>' panicked at crates/compiler/can/src/expr.rs:1130:41:
a Expr::TaskAwaitBang expression was not completed removed in desugar_value_def_suffixed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


There was an unrecoverable error in the Roc compiler. The `roc check` command can sometimes give a more helpful error report than other commands.
```

The LSP is giving me this error

```sh
Diagnostics:
1. INDENT ENDS AFTER EXPRESSION
   
   I am partway through parsing an expression, but I got stuck
   here:
   
   9│      expect 1 == 
                      ^
   
   Looks like the indentation ends prematurely here. Did you
   mean to have another expression after this line?

```

## Source Code
```roc
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.10.0/vNe6s9hWzoTZtFmNkvEICPErI9ptji_ySjicO6CkucY.tar.br" }
    imports [pf.Stdout, pf.Task]
    provides [main] to pf

total = addAndStringify { birds: -5, iguanas: 7 }

main =
    expect 1 == 2
    Stdout.line! "There are $(total) animals."


## This is a test
##
## x = 2
addAndStringify = \counts ->
    dbg "test"
    sum = counts.birds + counts.iguanas

    if sum == 0 then
        ""
    else
        Num.toStr sum


expect
  temp = addAndStringify { birds: 1, iguanas: 1}
  temp == "2"
```
## This is my roc version
```
roc nightly pre-release, built from commit 9fcd5a3 on Mo 27 Mai 2024 09:01:55 UTC
```

## OS info
```sh
Operating System: Ubuntu 22.04.4 LTS
Kernel: Linux 6.5.0-35-generic
```

**Comment by lukewilliamboswell** [comment] 2024-06-01 23:19
Thank you for logging this bug.

@kdziamura

**Comment by kdziamura** [comment] 2024-06-03 12:29
Found the root cause. Please assign it to me

**Closed** 2024-06-03 16:24 UTC
