### ISSUE TITLE
Online REPL crashes compiling simple function

### ISSUE THREAD

**Issue by andyferris** [roc-lang/roc#6705] opened 2024-05-02 13:25 UTC
The function `\x -> x + 1` miscompiles on the wasm target. It seems to get confused between `i64` and `i32` (although at this point I'm not sure why it is compiled at all, until we know the concrete type of `x`?).

This (obviously) works fine on other roc versions, like `roc repl` on linux x86_64.

```
» \x -> x + 1

JsValue(CompileError: WebAssembly.instantiate(): Compiling function #1290 failed: call[0] expected type i64, found local.get of type i32 @+9798
CompileError: WebAssembly.instantiate(): Compiling function #1290 failed: call[0] expected type i64, found local.get of type i32 @+9798) : 
```

Note: This is distinct to #5307 as `f = \x -> x + 1` gives the same error.

**Comment by skyqrose** [comment] 2024-11-23 18:17
I don't see a error with `f = \x -> x + 1`

```
» \x -> x + 1

JsValue(CompileError: wasm validation error: at offset 10218: type mismatch: expression has type i32 but expected i64
) : 
» \a, b -> a + b

JsValue(CompileError: wasm validation error: at offset 10214: type mismatch: expression has type i32 but expected i64
) : 
» f = \x -> x + 1

 : Num a -> Num a
```

So I'm pretty sure this is a duplicate of #5307

**Closed by skyqrose** 2024-11-23 18:17 UTC
