### ISSUE TITLE
REPL crashes when attempting to shadow a previous definition

### ISSUE THREAD

**Issue by basile-henry** [roc-lang/roc#5846] opened 2023-09-23 10:38 UTC
```elm
» x = 2

2 : Num *
» x = 3
panicked at 'not yet implemented', crates/compiler/mono/src/ir.rs:2738:23

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://www.roc-lang.org/repl/roc_repl_wasm.js:314:21)
    at console_error_panic_hook::hook::h700c986c2a10d220 (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[1195]:0x33fedb)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[2644]:0x3b2b78)
    at std::panicking::begin_panic_handler::{{closure}}::h1e17bad04a5713a4 (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[3017]:0x3c3a80)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h63adae5c31458c4b (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[5082]:0x3ec23f)
    at rust_begin_unwind (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4325]:0x3e5a09)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[4389]:0x3e69c2)
    at core::panicking::panic::h2f041bf6aa990dfd (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[3963]:0x3df222)
    at roc_mono::ir::from_can_let::h99c641d3b98cec04 (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[123]:0x19d1a6)
    at roc_mono::ir::from_can::h0e4124a9ef668c69 (https://www.roc-lang.org/repl/roc_repl_wasm_bg.wasm:wasm-function[161]:0x1d435c)
```

**Comment by kukimik** [comment] 2024-05-06 13:29
Duplicate of #6315.

**Closed** 2024-05-06 13:57 UTC
