### ISSUE TITLE
Pattern matching tuple of closed tag unions does not recognise all possibilities are covered

### ISSUE THREAD

**Issue by Wollantine** [roc-lang/roc#6154] opened 2023-12-02 16:47 UTC
## Setup

In the REPL, input the following:

```
Union : [A, B]

checkTuple : Union, Union -> Nat
checkTuple = \a, b ->
  when (a, b) is
    (A, _) -> 0
    (B, A) -> 1
    (B, B) -> 2
```

## Expected

The pattern matching covers all cases and compiles.

## Actual

```
── UNSAFE PATTERN ──────────────────────────────────────────────────────────────

This when does not cover all the possibilities:

 8│>        when (a, b) is
 9│>          (A, _) -> 0
10│>          (B, A) -> 1
11│>          (B, B) -> 2

Other possibilities include:

    ( B, _ )
```

**Comment by Anton-4** [comment] 2023-12-02 16:51
Thanks for reporting this @kwirke!
This appears to be identical to #5530.
But we can keep this issue open as an extra test case, to make sure the #5530 fix is solid when it lands.

**Comment by kwirke** [comment] 2023-12-02 23:17
Sorry for the duplicity, then! I did a fast search but couldn't find a similar issue.
I can only imagine the data storm you have to deal with, now that Roc is announced. Feel free to close this one whenever fits you best.

**Comment by Anton-4** [comment] 2023-12-04 11:36
> Sorry for the duplicity, then!

No problem at all :)

**Comment by skyqrose** [comment] 2024-11-03 02:37
I've linked to this example from #6154. Closing this one as a duplicate of that one to keep everything all in one place.

**Closed by skyqrose** 2024-11-03 02:37 UTC
