### ISSUE TITLE
Optional record field type error

### ISSUE THREAD

**Issue by bhansconnect** [roc-lang/roc#5444] opened 2023-05-25 16:19 UTC
Apparently using an optional record field as both optional and required can break type checking:

put this in repl or any file and roc check it:
```coffee
f : { val ? U64 } -> { val: U64 } 
f = \{val ? 7} -> {val}

g : {} -> { val: U64 } 
g = \{} -> f {val: 9}

h : {} -> { val: U64 } 
h = \{} -> f {}
```

will get:
```
── TYPE MISMATCH ───────────────────────────────────────────────────────────────

This 1st argument to f has an unexpected type:

11│      h = \{} -> f {}
                      ^^

The argument is a record of type:

    {}

But f needs its 1st argument to be:

    { val : Int Unsigned64 }

Tip: Looks like the val field is missing.
```

**Comment by jecaro** [comment] 2023-11-29 09:16
Having worked a bit on the issue, I am logging here my progress. I came up with a simpler repro that can be added to
`crates/compiler/solve/tests/solve_expr.rs`

```rust
    #[test]
    fn optional_field_bug() {
        infer_eq_without_problem(
            indoc!(
                r#"
                f : { val ? Bool }  -> Bool
                f = \{val ? Bool.false} -> val

                g = f {val: Bool.true}

                f
                "#
            ),
            "{ val ? Bool } -> Bool",
        );
    }
```
That test fails with:
```
---- solve_expr::optional_field_bug stdout ----
thread 'solve_expr::optional_field_bug' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<{ val : Bool } -> Bool
>{ val ? Bool } -> Bool
```

Somehow it seems that type-checking the `g` function changes the signature of `f`. Other interesting observations are:
- removing the signature of `f` makes it work as expected. The inferred type of `f` is rightly `{ val ? Bool }* -> Bool` in this case
- in the same vein, using the type `{ val ? Bool }* -> Bool` for `f` also works as expected

**Comment by skyqrose** [comment] 2024-11-23 20:46
Duplicate of https://github.com/roc-lang/roc/issues/6423

**Closed by skyqrose** 2024-11-23 20:46 UTC
Labels: bug, type checking, E-medium
