### ISSUE TITLE
Site REPL - crashes on shadowing instead of nice error

### ISSUE THREAD

**Issue by felix-alonso** [roc-lang/roc#6025] opened 2023-11-20 16:00 UTC
Here are the steps to reproduce it:

- type in `x = 1`
- type in `inc = \x -> x + 1`
- type in `inc 1`

You get the following error:

    Roc failed with message: “Shadowing { original_region: @49-50, shadow: @63-64 Ident(IdentStr { string: “x” }), kind: Variable }”

If you refresh the page and do the following, it works fine:

- type in `inc = \x -> x + 1`
- type in `inc 1`

Here is a screenshot of the interaction:

<img width="522" alt="image" src="https://github.com/roc-lang/roc/assets/11393098/19f59118-e700-47ee-9844-7aff474bdd35">

**Comment by rtfeldman** [comment] 2023-11-20 17:53
Thanks for the report @felix-alonso!

@brian-carroll mentioned that this used to display the error properly on the web repl, and it seems like we introduced a regression in the error reporting during a change to make it share more code with the CLI repl. 😅

**Comment by brian-carroll** [comment] 2023-11-20 22:40
@rtfeldman I think you're referring to an unrelated issue! This _is_ displaying the error properly! It's right there in red. And the REPL continues working after this error. In that other discussion, it stopped working.

**Comment by brian-carroll** [comment] 2023-11-20 22:40
What exactly is the problem here? Shadowing errors are part of Roc's design. Reasonable people may disagree with choices like this, but right now that's the intended behaviour. So what is the bug?

**Comment by brian-carroll** [comment] 2023-11-20 22:44
Also this does not look like it's specific to the REPL. I haven't tested it, but it is not coming from anything that is different in REPL mode than batch compilation mode.

**Comment by felix-alonso** [comment] 2023-11-20 22:49
Hey @brian-carroll,

This was a misunderstanding on my part. I assumed the lack of shadowing wouldn't extend to lambda arguments since I figured they would correspond to a new scope. Richard suggested I post the issue in this repo on [lobste.rs](https://lobste.rs/s/lskhwr/roc_programming_language#c_1awkjl). 

Since this is expected behavior feel free to close this issue. I didn't mean to be a bother. 

---

Congrats on the new website!

**Comment by brian-carroll** [comment] 2023-11-20 22:50
Oh OK thanks!
Yeah this is meant to be an error but maybe we should be handling it more gracefully.

**Comment by brian-carroll** [comment] 2023-11-20 22:51
Yeah the shadowing rules are pretty tough but that's the current design.

**Comment by brian-carroll** [comment] 2023-11-20 22:51
@rtfeldman do we insert a `crash` for shadowing errors?
If that's intended behaviour then we should close this issue.

**Closed** 2023-12-06 08:12 UTC
Labels: bug, repl
